### ISSUE TITLE
error Received malformed response from registry for "react-unmodal". The registry may be down.

### ISSUE THREAD

**Issue by mbenhenda** [thiagozf/demodal#1]
### Describe the bug

When running yarn start i have this issue:
`error Received malformed response from registry for "react-unmodal". The registry may be down.`

### Your minimal, reproducible example

typescript

### Steps to reproduce

1. run npm install

### Expected behavior

The library  should be installed

### How often does this bug happen?

Every time

### Platform

-Windows
- Command line

### react-unmodal version

latest

### TypeScript version

4.1.2

**Comment by thiagozf** [comment]
Hello @mbenhenda.

Looks like an intermittent issue with NPM registry. There used to be a package with the same name, but it was deleted some time ago. I think this is somehow causing the issue. I've contacted npmjs support and still waiting their response, hope they fix it soon. If they don't, I'll rename the package.

**Comment by thiagozf** [comment]
Since npm support is ~trash~ unresponsive, I've renamed this package from "react-unmodal" to "demodal". Please, check this [CodeSandbox](https://codesandbox.io/s/github/thiagozf/demodal/tree/main/examples/basic) for basic usage reference.
